package DataDictionaryNew.Java.sandbox;

/*Generated by MPS */


public class Mesto {
  private int mestoId;
  private String naziv;
  public Mesto() {
  }
  public void setMestoId(int newValue) {
    mestoId = newValue;
  }
  public void setNaziv(String newValue) {
    naziv = newValue;
  }
  public int getMestoId() {
    return mestoId;
  }
  public String getNaziv() {
    return naziv;
  }
}
