package DataDictionaryNew.Java.sandbox;

/*Generated by MPS */


public class Ucesnik {
  private String ime;
  private String imeRoditelja;
  private String prezime;
  public Ucesnik() {
  }
  public void setIme(String newValue) {
    ime = newValue;
  }
  public void setImeRoditelja(String newValue) {
    imeRoditelja = newValue;
  }
  public void setPrezime(String newValue) {
    prezime = newValue;
  }
  public String getIme() {
    return ime;
  }
  public String getImeRoditelja() {
    return imeRoditelja;
  }
  public String getPrezime() {
    return prezime;
  }
}
