package DataDictionary.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class ExclusiveSpecializationInLine_BehaviorDescriptor extends AbstractInLineStructure_BehaviorDescriptor {
  public String virtual_getFieldName_186827262372768005(SNode __thisNode__) {
    return null;
  }
  public String virtual_getterName_186827262372605446(SNode __thisNode__) {
    return null;
  }
  public String virtual_setterName_186827262372617471(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "DataDictionary.structure.ExclusiveSpecializationInLine";
  }

}
